name: note_app
description: A lightweight Notes app scaffold
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.0
  uuid: ^3.0.6
  sqflite: ^2.2.8
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.15.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
