name: note_app
description: A lightweight Notes app scaffold
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  shared_preferences: ^2.0.15
  reorderables: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  
  # Assets configuration
  assets:
    - assets/images/
